#pragma once

#include "Core/Macros/UtilMacros.h"
#include "Core/Template/TemplateUtil.h"
#include "WindowsPlatform/WindowsTypes.h"

#include <stdint.h>

enum class DXGI_FORMAT : uint32_t
{
	DXGI_FORMAT_UNKNOWN = 0,
	DXGI_FORMAT_R32G32B32A32_TYPELESS = 1,
	DXGI_FORMAT_R32G32B32A32_FLOAT = 2,
	DXGI_FORMAT_R32G32B32A32_UINT = 3,
	DXGI_FORMAT_R32G32B32A32_SINT = 4,
	DXGI_FORMAT_R32G32B32_TYPELESS = 5,
	DXGI_FORMAT_R32G32B32_FLOAT = 6,
	DXGI_FORMAT_R32G32B32_UINT = 7,
	DXGI_FORMAT_R32G32B32_SINT = 8,
	DXGI_FORMAT_R16G16B16A16_TYPELESS = 9,
	DXGI_FORMAT_R16G16B16A16_FLOAT = 10,
	DXGI_FORMAT_R16G16B16A16_UNORM = 11,
	DXGI_FORMAT_R16G16B16A16_UINT = 12,
	DXGI_FORMAT_R16G16B16A16_SNORM = 13,
	DXGI_FORMAT_R16G16B16A16_SINT = 14,
	DXGI_FORMAT_R32G32_TYPELESS = 15,
	DXGI_FORMAT_R32G32_FLOAT = 16,
	DXGI_FORMAT_R32G32_UINT = 17,
	DXGI_FORMAT_R32G32_SINT = 18,
	DXGI_FORMAT_R32G8X24_TYPELESS = 19,
	DXGI_FORMAT_D32_FLOAT_S8X24_UINT = 20,
	DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS = 21,
	DXGI_FORMAT_X32_TYPELESS_G8X24_UINT = 22,
	DXGI_FORMAT_R10G10B10A2_TYPELESS = 23,
	DXGI_FORMAT_R10G10B10A2_UNORM = 24,
	DXGI_FORMAT_R10G10B10A2_UINT = 25,
	DXGI_FORMAT_R11G11B10_FLOAT = 26,
	DXGI_FORMAT_R8G8B8A8_TYPELESS = 27,
	DXGI_FORMAT_R8G8B8A8_UNORM = 28,
	DXGI_FORMAT_R8G8B8A8_UNORM_SRGB = 29,
	DXGI_FORMAT_R8G8B8A8_UINT = 30,
	DXGI_FORMAT_R8G8B8A8_SNORM = 31,
	DXGI_FORMAT_R8G8B8A8_SINT = 32,
	DXGI_FORMAT_R16G16_TYPELESS = 33,
	DXGI_FORMAT_R16G16_FLOAT = 34,
	DXGI_FORMAT_R16G16_UNORM = 35,
	DXGI_FORMAT_R16G16_UINT = 36,
	DXGI_FORMAT_R16G16_SNORM = 37,
	DXGI_FORMAT_R16G16_SINT = 38,
	DXGI_FORMAT_R32_TYPELESS = 39,
	DXGI_FORMAT_D32_FLOAT = 40,
	DXGI_FORMAT_R32_FLOAT = 41,
	DXGI_FORMAT_R32_UINT = 42,
	DXGI_FORMAT_R32_SINT = 43,
	DXGI_FORMAT_R24G8_TYPELESS = 44,
	DXGI_FORMAT_D24_UNORM_S8_UINT = 45,
	DXGI_FORMAT_R24_UNORM_X8_TYPELESS = 46,
	DXGI_FORMAT_X24_TYPELESS_G8_UINT = 47,
	DXGI_FORMAT_R8G8_TYPELESS = 48,
	DXGI_FORMAT_R8G8_UNORM = 49,
	DXGI_FORMAT_R8G8_UINT = 50,
	DXGI_FORMAT_R8G8_SNORM = 51,
	DXGI_FORMAT_R8G8_SINT = 52,
	DXGI_FORMAT_R16_TYPELESS = 53,
	DXGI_FORMAT_R16_FLOAT = 54,
	DXGI_FORMAT_D16_UNORM = 55,
	DXGI_FORMAT_R16_UNORM = 56,
	DXGI_FORMAT_R16_UINT = 57,
	DXGI_FORMAT_R16_SNORM = 58,
	DXGI_FORMAT_R16_SINT = 59,
	DXGI_FORMAT_R8_TYPELESS = 60,
	DXGI_FORMAT_R8_UNORM = 61,
	DXGI_FORMAT_R8_UINT = 62,
	DXGI_FORMAT_R8_SNORM = 63,
	DXGI_FORMAT_R8_SINT = 64,
	DXGI_FORMAT_A8_UNORM = 65,
	DXGI_FORMAT_R1_UNORM = 66,
	DXGI_FORMAT_R9G9B9E5_SHAREDEXP = 67,
	DXGI_FORMAT_R8G8_B8G8_UNORM = 68,
	DXGI_FORMAT_G8R8_G8B8_UNORM = 69,
	DXGI_FORMAT_BC1_TYPELESS = 70,
	DXGI_FORMAT_BC1_UNORM = 71,
	DXGI_FORMAT_BC1_UNORM_SRGB = 72,
	DXGI_FORMAT_BC2_TYPELESS = 73,
	DXGI_FORMAT_BC2_UNORM = 74,
	DXGI_FORMAT_BC2_UNORM_SRGB = 75,
	DXGI_FORMAT_BC3_TYPELESS = 76,
	DXGI_FORMAT_BC3_UNORM = 77,
	DXGI_FORMAT_BC3_UNORM_SRGB = 78,
	DXGI_FORMAT_BC4_TYPELESS = 79,
	DXGI_FORMAT_BC4_UNORM = 80,
	DXGI_FORMAT_BC4_SNORM = 81,
	DXGI_FORMAT_BC5_TYPELESS = 82,
	DXGI_FORMAT_BC5_UNORM = 83,
	DXGI_FORMAT_BC5_SNORM = 84,
	DXGI_FORMAT_B5G6R5_UNORM = 85,
	DXGI_FORMAT_B5G5R5A1_UNORM = 86,
	DXGI_FORMAT_B8G8R8A8_UNORM = 87,
	DXGI_FORMAT_B8G8R8X8_UNORM = 88,
	DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM = 89,
	DXGI_FORMAT_B8G8R8A8_TYPELESS = 90,
	DXGI_FORMAT_B8G8R8A8_UNORM_SRGB = 91,
	DXGI_FORMAT_B8G8R8X8_TYPELESS = 92,
	DXGI_FORMAT_B8G8R8X8_UNORM_SRGB = 93,
	DXGI_FORMAT_BC6H_TYPELESS = 94,
	DXGI_FORMAT_BC6H_UF16 = 95,
	DXGI_FORMAT_BC6H_SF16 = 96,
	DXGI_FORMAT_BC7_TYPELESS = 97,
	DXGI_FORMAT_BC7_UNORM = 98,
	DXGI_FORMAT_BC7_UNORM_SRGB = 99,
	DXGI_FORMAT_AYUV = 100,
	DXGI_FORMAT_Y410 = 101,
	DXGI_FORMAT_Y416 = 102,
	DXGI_FORMAT_NV12 = 103,
	DXGI_FORMAT_P010 = 104,
	DXGI_FORMAT_P016 = 105,
	DXGI_FORMAT_420_OPAQUE = 106,
	DXGI_FORMAT_YUY2 = 107,
	DXGI_FORMAT_Y210 = 108,
	DXGI_FORMAT_Y216 = 109,
	DXGI_FORMAT_NV11 = 110,
	DXGI_FORMAT_AI44 = 111,
	DXGI_FORMAT_IA44 = 112,
	DXGI_FORMAT_P8 = 113,
	DXGI_FORMAT_A8P8 = 114,
	DXGI_FORMAT_B4G4R4A4_UNORM = 115,

	DXGI_FORMAT_P208 = 130,
	DXGI_FORMAT_V208 = 131,
	DXGI_FORMAT_V408 = 132,


	DXGI_FORMAT_FORCE_UINT = 0xffffffff
};

struct GUID
{
	unsigned long  Data1;
	unsigned short Data2;
	unsigned short Data3;
	unsigned char  Data4[8];
};

struct RECT
{
	int32_t    left;
	int32_t    top;
	int32_t    right;
	int32_t    bottom;
};

struct DXGI_SAMPLE_DESC
{
	uint32_t Count;
	uint32_t Quality;
};

enum class D3D_DRIVER_TYPE
{
	D3D_DRIVER_TYPE_UNKNOWN = 0,
	D3D_DRIVER_TYPE_HARDWARE = (D3D_DRIVER_TYPE_UNKNOWN + 1),
	D3D_DRIVER_TYPE_REFERENCE = (D3D_DRIVER_TYPE_HARDWARE + 1),
	D3D_DRIVER_TYPE_NULL = (D3D_DRIVER_TYPE_REFERENCE + 1),
	D3D_DRIVER_TYPE_SOFTWARE = (D3D_DRIVER_TYPE_NULL + 1),
	D3D_DRIVER_TYPE_WARP = (D3D_DRIVER_TYPE_SOFTWARE + 1)
};


enum class D3D_FEATURE_LEVEL
{
	D3D_FEATURE_LEVEL_9_1 = 0x9100,
	D3D_FEATURE_LEVEL_9_2 = 0x9200,
	D3D_FEATURE_LEVEL_9_3 = 0x9300,
	D3D_FEATURE_LEVEL_10_0 = 0xa000,
	D3D_FEATURE_LEVEL_10_1 = 0xa100,
	D3D_FEATURE_LEVEL_11_0 = 0xb000,
	D3D_FEATURE_LEVEL_11_1 = 0xb100,
	D3D_FEATURE_LEVEL_12_0 = 0xc000,
	D3D_FEATURE_LEVEL_12_1 = 0xc100
};

constexpr uint32_t D3D_FL9_1_REQ_TEXTURE1D_U_DIMENSION = 2048;
constexpr uint32_t D3D_FL9_3_REQ_TEXTURE1D_U_DIMENSION = 4096;
constexpr uint32_t D3D_FL9_1_REQ_TEXTURE2D_U_OR_V_DIMENSION = 2048;
constexpr uint32_t D3D_FL9_3_REQ_TEXTURE2D_U_OR_V_DIMENSION = 4096;
constexpr uint32_t D3D_FL9_1_REQ_TEXTURECUBE_DIMENSION = 512;
constexpr uint32_t D3D_FL9_3_REQ_TEXTURECUBE_DIMENSION = 4096;
constexpr uint32_t D3D_FL9_1_REQ_TEXTURE3D_U_V_OR_W_DIMENSION = 256;
constexpr uint32_t D3D_FL9_1_DEFAULT_MAX_ANISOTROPY = 2;
constexpr uint32_t D3D_FL9_1_IA_PRIMITIVE_MAX_COUNT = 65535;
constexpr uint32_t D3D_FL9_2_IA_PRIMITIVE_MAX_COUNT = 1048575;
constexpr uint32_t D3D_FL9_1_SIMULTANEOUS_RENDER_TARGET_COUNT = 1;
constexpr uint32_t D3D_FL9_3_SIMULTANEOUS_RENDER_TARGET_COUNT = 4;
constexpr uint32_t D3D_FL9_1_MAX_TEXTURE_REPEAT = 128;
constexpr uint32_t D3D_FL9_2_MAX_TEXTURE_REPEAT = 2048;
constexpr uint32_t D3D_FL9_3_MAX_TEXTURE_REPEAT = 8192;

enum class D3D_PRIMITIVE_TOPOLOGY
{
	D3D_PRIMITIVE_TOPOLOGY_UNDEFINED = 0,
	D3D_PRIMITIVE_TOPOLOGY_POINTLIST = 1,
	D3D_PRIMITIVE_TOPOLOGY_LINELIST = 2,
	D3D_PRIMITIVE_TOPOLOGY_LINESTRIP = 3,
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4,
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = 5,
	D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = 10,
	D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = 11,
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = 12,
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = 13,
	D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST = 33,
	D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST = 34,
	D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST = 35,
	D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST = 36,
	D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST = 37,
	D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST = 38,
	D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST = 39,
	D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST = 40,
	D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST = 41,
	D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST = 42,
	D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST = 43,
	D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST = 44,
	D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST = 45,
	D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST = 46,
	D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST = 47,
	D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST = 48,
	D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST = 49,
	D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST = 50,
	D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST = 51,
	D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST = 52,
	D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST = 53,
	D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST = 54,
	D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST = 55,
	D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST = 56,
	D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST = 57,
	D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST = 58,
	D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST = 59,
	D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST = 60,
	D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST = 61,
	D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST = 62,
	D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST = 63,
	D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST = 64,
	D3D10_PRIMITIVE_TOPOLOGY_UNDEFINED = D3D_PRIMITIVE_TOPOLOGY_UNDEFINED,
	D3D10_PRIMITIVE_TOPOLOGY_POINTLIST = D3D_PRIMITIVE_TOPOLOGY_POINTLIST,
	D3D10_PRIMITIVE_TOPOLOGY_LINELIST = D3D_PRIMITIVE_TOPOLOGY_LINELIST,
	D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP,
	D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
	D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
	D3D10_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ,
	D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ,
	D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ,
	D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ,
	D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED = D3D_PRIMITIVE_TOPOLOGY_UNDEFINED,
	D3D11_PRIMITIVE_TOPOLOGY_POINTLIST = D3D_PRIMITIVE_TOPOLOGY_POINTLIST,
	D3D11_PRIMITIVE_TOPOLOGY_LINELIST = D3D_PRIMITIVE_TOPOLOGY_LINELIST,
	D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP,
	D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
	D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
	D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ,
	D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ,
	D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ,
	D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ,
	D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST,
	D3D11_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST = D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST
};


enum class D3D_PRIMITIVE
{
	D3D_PRIMITIVE_UNDEFINED = 0,
	D3D_PRIMITIVE_POINT = 1,
	D3D_PRIMITIVE_LINE = 2,
	D3D_PRIMITIVE_TRIANGLE = 3,
	D3D_PRIMITIVE_LINE_ADJ = 6,
	D3D_PRIMITIVE_TRIANGLE_ADJ = 7,
	D3D_PRIMITIVE_1_CONTROL_POINT_PATCH = 8,
	D3D_PRIMITIVE_2_CONTROL_POINT_PATCH = 9,
	D3D_PRIMITIVE_3_CONTROL_POINT_PATCH = 10,
	D3D_PRIMITIVE_4_CONTROL_POINT_PATCH = 11,
	D3D_PRIMITIVE_5_CONTROL_POINT_PATCH = 12,
	D3D_PRIMITIVE_6_CONTROL_POINT_PATCH = 13,
	D3D_PRIMITIVE_7_CONTROL_POINT_PATCH = 14,
	D3D_PRIMITIVE_8_CONTROL_POINT_PATCH = 15,
	D3D_PRIMITIVE_9_CONTROL_POINT_PATCH = 16,
	D3D_PRIMITIVE_10_CONTROL_POINT_PATCH = 17,
	D3D_PRIMITIVE_11_CONTROL_POINT_PATCH = 18,
	D3D_PRIMITIVE_12_CONTROL_POINT_PATCH = 19,
	D3D_PRIMITIVE_13_CONTROL_POINT_PATCH = 20,
	D3D_PRIMITIVE_14_CONTROL_POINT_PATCH = 21,
	D3D_PRIMITIVE_15_CONTROL_POINT_PATCH = 22,
	D3D_PRIMITIVE_16_CONTROL_POINT_PATCH = 23,
	D3D_PRIMITIVE_17_CONTROL_POINT_PATCH = 24,
	D3D_PRIMITIVE_18_CONTROL_POINT_PATCH = 25,
	D3D_PRIMITIVE_19_CONTROL_POINT_PATCH = 26,
	D3D_PRIMITIVE_20_CONTROL_POINT_PATCH = 27,
	D3D_PRIMITIVE_21_CONTROL_POINT_PATCH = 28,
	D3D_PRIMITIVE_22_CONTROL_POINT_PATCH = 29,
	D3D_PRIMITIVE_23_CONTROL_POINT_PATCH = 30,
	D3D_PRIMITIVE_24_CONTROL_POINT_PATCH = 31,
	D3D_PRIMITIVE_25_CONTROL_POINT_PATCH = 32,
	D3D_PRIMITIVE_26_CONTROL_POINT_PATCH = 33,
	D3D_PRIMITIVE_27_CONTROL_POINT_PATCH = 34,
	D3D_PRIMITIVE_28_CONTROL_POINT_PATCH = 35,
	D3D_PRIMITIVE_29_CONTROL_POINT_PATCH = 36,
	D3D_PRIMITIVE_30_CONTROL_POINT_PATCH = 37,
	D3D_PRIMITIVE_31_CONTROL_POINT_PATCH = 38,
	D3D_PRIMITIVE_32_CONTROL_POINT_PATCH = 39,
	D3D10_PRIMITIVE_UNDEFINED = D3D_PRIMITIVE_UNDEFINED,
	D3D10_PRIMITIVE_POINT = D3D_PRIMITIVE_POINT,
	D3D10_PRIMITIVE_LINE = D3D_PRIMITIVE_LINE,
	D3D10_PRIMITIVE_TRIANGLE = D3D_PRIMITIVE_TRIANGLE,
	D3D10_PRIMITIVE_LINE_ADJ = D3D_PRIMITIVE_LINE_ADJ,
	D3D10_PRIMITIVE_TRIANGLE_ADJ = D3D_PRIMITIVE_TRIANGLE_ADJ,
	D3D11_PRIMITIVE_UNDEFINED = D3D_PRIMITIVE_UNDEFINED,
	D3D11_PRIMITIVE_POINT = D3D_PRIMITIVE_POINT,
	D3D11_PRIMITIVE_LINE = D3D_PRIMITIVE_LINE,
	D3D11_PRIMITIVE_TRIANGLE = D3D_PRIMITIVE_TRIANGLE,
	D3D11_PRIMITIVE_LINE_ADJ = D3D_PRIMITIVE_LINE_ADJ,
	D3D11_PRIMITIVE_TRIANGLE_ADJ = D3D_PRIMITIVE_TRIANGLE_ADJ,
	D3D11_PRIMITIVE_1_CONTROL_POINT_PATCH = D3D_PRIMITIVE_1_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_2_CONTROL_POINT_PATCH = D3D_PRIMITIVE_2_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_3_CONTROL_POINT_PATCH = D3D_PRIMITIVE_3_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_4_CONTROL_POINT_PATCH = D3D_PRIMITIVE_4_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_5_CONTROL_POINT_PATCH = D3D_PRIMITIVE_5_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_6_CONTROL_POINT_PATCH = D3D_PRIMITIVE_6_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_7_CONTROL_POINT_PATCH = D3D_PRIMITIVE_7_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_8_CONTROL_POINT_PATCH = D3D_PRIMITIVE_8_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_9_CONTROL_POINT_PATCH = D3D_PRIMITIVE_9_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_10_CONTROL_POINT_PATCH = D3D_PRIMITIVE_10_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_11_CONTROL_POINT_PATCH = D3D_PRIMITIVE_11_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_12_CONTROL_POINT_PATCH = D3D_PRIMITIVE_12_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_13_CONTROL_POINT_PATCH = D3D_PRIMITIVE_13_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_14_CONTROL_POINT_PATCH = D3D_PRIMITIVE_14_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_15_CONTROL_POINT_PATCH = D3D_PRIMITIVE_15_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_16_CONTROL_POINT_PATCH = D3D_PRIMITIVE_16_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_17_CONTROL_POINT_PATCH = D3D_PRIMITIVE_17_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_18_CONTROL_POINT_PATCH = D3D_PRIMITIVE_18_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_19_CONTROL_POINT_PATCH = D3D_PRIMITIVE_19_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_20_CONTROL_POINT_PATCH = D3D_PRIMITIVE_20_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_21_CONTROL_POINT_PATCH = D3D_PRIMITIVE_21_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_22_CONTROL_POINT_PATCH = D3D_PRIMITIVE_22_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_23_CONTROL_POINT_PATCH = D3D_PRIMITIVE_23_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_24_CONTROL_POINT_PATCH = D3D_PRIMITIVE_24_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_25_CONTROL_POINT_PATCH = D3D_PRIMITIVE_25_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_26_CONTROL_POINT_PATCH = D3D_PRIMITIVE_26_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_27_CONTROL_POINT_PATCH = D3D_PRIMITIVE_27_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_28_CONTROL_POINT_PATCH = D3D_PRIMITIVE_28_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_29_CONTROL_POINT_PATCH = D3D_PRIMITIVE_29_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_30_CONTROL_POINT_PATCH = D3D_PRIMITIVE_30_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_31_CONTROL_POINT_PATCH = D3D_PRIMITIVE_31_CONTROL_POINT_PATCH,
	D3D11_PRIMITIVE_32_CONTROL_POINT_PATCH = D3D_PRIMITIVE_32_CONTROL_POINT_PATCH
};


enum class D3D_SRV_DIMENSION
{
	D3D_SRV_DIMENSION_UNKNOWN = 0,
	D3D_SRV_DIMENSION_BUFFER = 1,
	D3D_SRV_DIMENSION_TEXTURE1D = 2,
	D3D_SRV_DIMENSION_TEXTURE1DARRAY = 3,
	D3D_SRV_DIMENSION_TEXTURE2D = 4,
	D3D_SRV_DIMENSION_TEXTURE2DARRAY = 5,
	D3D_SRV_DIMENSION_TEXTURE2DMS = 6,
	D3D_SRV_DIMENSION_TEXTURE2DMSARRAY = 7,
	D3D_SRV_DIMENSION_TEXTURE3D = 8,
	D3D_SRV_DIMENSION_TEXTURECUBE = 9,
	D3D_SRV_DIMENSION_TEXTURECUBEARRAY = 10,
	D3D_SRV_DIMENSION_BUFFEREX = 11,
	D3D10_SRV_DIMENSION_UNKNOWN = D3D_SRV_DIMENSION_UNKNOWN,
	D3D10_SRV_DIMENSION_BUFFER = D3D_SRV_DIMENSION_BUFFER,
	D3D10_SRV_DIMENSION_TEXTURE1D = D3D_SRV_DIMENSION_TEXTURE1D,
	D3D10_SRV_DIMENSION_TEXTURE1DARRAY = D3D_SRV_DIMENSION_TEXTURE1DARRAY,
	D3D10_SRV_DIMENSION_TEXTURE2D = D3D_SRV_DIMENSION_TEXTURE2D,
	D3D10_SRV_DIMENSION_TEXTURE2DARRAY = D3D_SRV_DIMENSION_TEXTURE2DARRAY,
	D3D10_SRV_DIMENSION_TEXTURE2DMS = D3D_SRV_DIMENSION_TEXTURE2DMS,
	D3D10_SRV_DIMENSION_TEXTURE2DMSARRAY = D3D_SRV_DIMENSION_TEXTURE2DMSARRAY,
	D3D10_SRV_DIMENSION_TEXTURE3D = D3D_SRV_DIMENSION_TEXTURE3D,
	D3D10_SRV_DIMENSION_TEXTURECUBE = D3D_SRV_DIMENSION_TEXTURECUBE,
	D3D10_1_SRV_DIMENSION_UNKNOWN = D3D_SRV_DIMENSION_UNKNOWN,
	D3D10_1_SRV_DIMENSION_BUFFER = D3D_SRV_DIMENSION_BUFFER,
	D3D10_1_SRV_DIMENSION_TEXTURE1D = D3D_SRV_DIMENSION_TEXTURE1D,
	D3D10_1_SRV_DIMENSION_TEXTURE1DARRAY = D3D_SRV_DIMENSION_TEXTURE1DARRAY,
	D3D10_1_SRV_DIMENSION_TEXTURE2D = D3D_SRV_DIMENSION_TEXTURE2D,
	D3D10_1_SRV_DIMENSION_TEXTURE2DARRAY = D3D_SRV_DIMENSION_TEXTURE2DARRAY,
	D3D10_1_SRV_DIMENSION_TEXTURE2DMS = D3D_SRV_DIMENSION_TEXTURE2DMS,
	D3D10_1_SRV_DIMENSION_TEXTURE2DMSARRAY = D3D_SRV_DIMENSION_TEXTURE2DMSARRAY,
	D3D10_1_SRV_DIMENSION_TEXTURE3D = D3D_SRV_DIMENSION_TEXTURE3D,
	D3D10_1_SRV_DIMENSION_TEXTURECUBE = D3D_SRV_DIMENSION_TEXTURECUBE,
	D3D10_1_SRV_DIMENSION_TEXTURECUBEARRAY = D3D_SRV_DIMENSION_TEXTURECUBEARRAY,
	D3D11_SRV_DIMENSION_UNKNOWN = D3D_SRV_DIMENSION_UNKNOWN,
	D3D11_SRV_DIMENSION_BUFFER = D3D_SRV_DIMENSION_BUFFER,
	D3D11_SRV_DIMENSION_TEXTURE1D = D3D_SRV_DIMENSION_TEXTURE1D,
	D3D11_SRV_DIMENSION_TEXTURE1DARRAY = D3D_SRV_DIMENSION_TEXTURE1DARRAY,
	D3D11_SRV_DIMENSION_TEXTURE2D = D3D_SRV_DIMENSION_TEXTURE2D,
	D3D11_SRV_DIMENSION_TEXTURE2DARRAY = D3D_SRV_DIMENSION_TEXTURE2DARRAY,
	D3D11_SRV_DIMENSION_TEXTURE2DMS = D3D_SRV_DIMENSION_TEXTURE2DMS,
	D3D11_SRV_DIMENSION_TEXTURE2DMSARRAY = D3D_SRV_DIMENSION_TEXTURE2DMSARRAY,
	D3D11_SRV_DIMENSION_TEXTURE3D = D3D_SRV_DIMENSION_TEXTURE3D,
	D3D11_SRV_DIMENSION_TEXTURECUBE = D3D_SRV_DIMENSION_TEXTURECUBE,
	D3D11_SRV_DIMENSION_TEXTURECUBEARRAY = D3D_SRV_DIMENSION_TEXTURECUBEARRAY,
	D3D11_SRV_DIMENSION_BUFFEREX = D3D_SRV_DIMENSION_BUFFEREX
};

enum class ED3DShaderTarget
{
	VS_5_0,
	HS_5_0,
	DS_5_0,
	GS_5_0,
	PS_5_0,
	CS_5_0,
	VS_6_0,
	HS_6_0,
	DS_6_0,
	GS_6_0,
	PS_6_0,
	CS_6_0,
	VS_6_4,
	HS_6_4,
	DS_6_4,
	GS_6_4,
	PS_6_4,
	CS_6_4,

	Num,
	Error = TErrorEnumValue<ED3DShaderTarget>
};

enum class EShaderCompileFlag
{
	D3DCOMPILE_NONE = 0,
	D3DCOMPILE_DEBUG = 1 << 0,
	D3DCOMPILE_SKIP_VALIDATION = 1 << 1,
	D3DCOMPILE_SKIP_OPTIMIZATION = 1 << 2,
	D3DCOMPILE_PACK_MATRIX_ROW_MAJOR = 1 << 3,
	D3DCOMPILE_PACK_MATRIX_COLUMN_MAJOR = 1 << 4,
	D3DCOMPILE_PARTIAL_PRECISION = 1 << 5,
	D3DCOMPILE_FORCE_VS_SOFTWARE_NO_OPT = 1 << 6,
	D3DCOMPILE_FORCE_PS_SOFTWARE_NO_OPT = 1 << 7,
	D3DCOMPILE_NO_PRESHADER = 1 << 8,
	D3DCOMPILE_AVOID_FLOW_CONTROL = 1 << 9,
	D3DCOMPILE_PREFER_FLOW_CONTROL = 1 << 10,
	D3DCOMPILE_ENABLE_STRICTNESS = 1 << 11,
	D3DCOMPILE_ENABLE_BACKWARDS_COMPATIBILITY = 1 << 12,
	D3DCOMPILE_IEEE_STRICTNESS = 1 << 13,
	D3DCOMPILE_OPTIMIZATION_LEVEL0 = 1 << 14,
	D3DCOMPILE_OPTIMIZATION_LEVEL1 = 0,
	D3DCOMPILE_OPTIMIZATION_LEVEL2 = 1 << 14 | 1 << 15,
	D3DCOMPILE_OPTIMIZATION_LEVEL3 = 1 << 15,
	D3DCOMPILE_RESERVED16 = 1 << 16,
	D3DCOMPILE_RESERVED17 = 1 << 17,
	D3DCOMPILE_WARNINGS_ARE_ERRORS = 1 << 18,
	D3DCOMPILE_RESOURCES_MAY_ALIAS = 1 << 19,
	D3DCOMPILE_ENABLE_UNBOUNDED_DESCRIPTOR_TABLES = 1 << 20,
	D3DCOMPILE_ALL_RESOURCES_BOUND = 1 << 21,
	D3DCOMPILE_DEBUG_NAME_FOR_SOURCE = 1 << 22,
	D3DCOMPILE_DEBUG_NAME_FOR_BINARY = 1 << 23,
};
REGIST_ENUM_FLAG(EShaderCompileFlag)

struct D3D_SHADER_MACRO
{
	const char* Name;
	const char* Definition;
};

enum class D3D_INCLUDE_TYPE
{
	D3D_INCLUDE_LOCAL = 0,
	D3D_INCLUDE_SYSTEM = (D3D_INCLUDE_LOCAL + 1),
	D3D10_INCLUDE_LOCAL = D3D_INCLUDE_LOCAL,
	D3D10_INCLUDE_SYSTEM = D3D_INCLUDE_SYSTEM,
	D3D_INCLUDE_FORCE_DWORD = 0x7fffffff
};

enum class D3D_SHADER_VARIABLE_CLASS
{
	D3D_SVC_SCALAR = 0,
	D3D_SVC_VECTOR = (D3D_SVC_SCALAR + 1),
	D3D_SVC_MATRIX_ROWS = (D3D_SVC_VECTOR + 1),
	D3D_SVC_MATRIX_COLUMNS = (D3D_SVC_MATRIX_ROWS + 1),
	D3D_SVC_OBJECT = (D3D_SVC_MATRIX_COLUMNS + 1),
	D3D_SVC_STRUCT = (D3D_SVC_OBJECT + 1),
	D3D_SVC_INTERFACE_CLASS = (D3D_SVC_STRUCT + 1),
	D3D_SVC_INTERFACE_POINTER = (D3D_SVC_INTERFACE_CLASS + 1),
	D3D10_SVC_SCALAR = D3D_SVC_SCALAR,
	D3D10_SVC_VECTOR = D3D_SVC_VECTOR,
	D3D10_SVC_MATRIX_ROWS = D3D_SVC_MATRIX_ROWS,
	D3D10_SVC_MATRIX_COLUMNS = D3D_SVC_MATRIX_COLUMNS,
	D3D10_SVC_OBJECT = D3D_SVC_OBJECT,
	D3D10_SVC_STRUCT = D3D_SVC_STRUCT,
	D3D11_SVC_INTERFACE_CLASS = D3D_SVC_INTERFACE_CLASS,
	D3D11_SVC_INTERFACE_POINTER = D3D_SVC_INTERFACE_POINTER,
	D3D_SVC_FORCE_DWORD = 0x7fffffff
};


enum class D3D_SHADER_VARIABLE_FLAGS
{
	D3D_SVF_USERPACKED = 1,
	D3D_SVF_USED = 2,
	D3D_SVF_INTERFACE_POINTER = 4,
	D3D_SVF_INTERFACE_PARAMETER = 8,
	D3D10_SVF_USERPACKED = D3D_SVF_USERPACKED,
	D3D10_SVF_USED = D3D_SVF_USED,
	D3D11_SVF_INTERFACE_POINTER = D3D_SVF_INTERFACE_POINTER,
	D3D11_SVF_INTERFACE_PARAMETER = D3D_SVF_INTERFACE_PARAMETER,
	D3D_SVF_FORCE_DWORD = 0x7fffffff
};


enum class D3D_SHADER_VARIABLE_TYPE
{
	D3D_SVT_VOID = 0,
	D3D_SVT_BOOL = 1,
	D3D_SVT_INT = 2,
	D3D_SVT_FLOAT = 3,
	D3D_SVT_STRING = 4,
	D3D_SVT_TEXTURE = 5,
	D3D_SVT_TEXTURE1D = 6,
	D3D_SVT_TEXTURE2D = 7,
	D3D_SVT_TEXTURE3D = 8,
	D3D_SVT_TEXTURECUBE = 9,
	D3D_SVT_SAMPLER = 10,
	D3D_SVT_SAMPLER1D = 11,
	D3D_SVT_SAMPLER2D = 12,
	D3D_SVT_SAMPLER3D = 13,
	D3D_SVT_SAMPLERCUBE = 14,
	D3D_SVT_PIXELSHADER = 15,
	D3D_SVT_VERTEXSHADER = 16,
	D3D_SVT_PIXELFRAGMENT = 17,
	D3D_SVT_VERTEXFRAGMENT = 18,
	D3D_SVT_UINT = 19,
	D3D_SVT_UINT8 = 20,
	D3D_SVT_GEOMETRYSHADER = 21,
	D3D_SVT_RASTERIZER = 22,
	D3D_SVT_DEPTHSTENCIL = 23,
	D3D_SVT_BLEND = 24,
	D3D_SVT_BUFFER = 25,
	D3D_SVT_CBUFFER = 26,
	D3D_SVT_TBUFFER = 27,
	D3D_SVT_TEXTURE1DARRAY = 28,
	D3D_SVT_TEXTURE2DARRAY = 29,
	D3D_SVT_RENDERTARGETVIEW = 30,
	D3D_SVT_DEPTHSTENCILVIEW = 31,
	D3D_SVT_TEXTURE2DMS = 32,
	D3D_SVT_TEXTURE2DMSARRAY = 33,
	D3D_SVT_TEXTURECUBEARRAY = 34,
	D3D_SVT_HULLSHADER = 35,
	D3D_SVT_DOMAINSHADER = 36,
	D3D_SVT_INTERFACE_POINTER = 37,
	D3D_SVT_COMPUTESHADER = 38,
	D3D_SVT_DOUBLE = 39,
	D3D_SVT_RWTEXTURE1D = 40,
	D3D_SVT_RWTEXTURE1DARRAY = 41,
	D3D_SVT_RWTEXTURE2D = 42,
	D3D_SVT_RWTEXTURE2DARRAY = 43,
	D3D_SVT_RWTEXTURE3D = 44,
	D3D_SVT_RWBUFFER = 45,
	D3D_SVT_BYTEADDRESS_BUFFER = 46,
	D3D_SVT_RWBYTEADDRESS_BUFFER = 47,
	D3D_SVT_STRUCTURED_BUFFER = 48,
	D3D_SVT_RWSTRUCTURED_BUFFER = 49,
	D3D_SVT_APPEND_STRUCTURED_BUFFER = 50,
	D3D_SVT_CONSUME_STRUCTURED_BUFFER = 51,
	D3D_SVT_MIN8FLOAT = 52,
	D3D_SVT_MIN10FLOAT = 53,
	D3D_SVT_MIN16FLOAT = 54,
	D3D_SVT_MIN12INT = 55,
	D3D_SVT_MIN16INT = 56,
	D3D_SVT_MIN16UINT = 57,
	D3D10_SVT_VOID = D3D_SVT_VOID,
	D3D10_SVT_BOOL = D3D_SVT_BOOL,
	D3D10_SVT_INT = D3D_SVT_INT,
	D3D10_SVT_FLOAT = D3D_SVT_FLOAT,
	D3D10_SVT_STRING = D3D_SVT_STRING,
	D3D10_SVT_TEXTURE = D3D_SVT_TEXTURE,
	D3D10_SVT_TEXTURE1D = D3D_SVT_TEXTURE1D,
	D3D10_SVT_TEXTURE2D = D3D_SVT_TEXTURE2D,
	D3D10_SVT_TEXTURE3D = D3D_SVT_TEXTURE3D,
	D3D10_SVT_TEXTURECUBE = D3D_SVT_TEXTURECUBE,
	D3D10_SVT_SAMPLER = D3D_SVT_SAMPLER,
	D3D10_SVT_SAMPLER1D = D3D_SVT_SAMPLER1D,
	D3D10_SVT_SAMPLER2D = D3D_SVT_SAMPLER2D,
	D3D10_SVT_SAMPLER3D = D3D_SVT_SAMPLER3D,
	D3D10_SVT_SAMPLERCUBE = D3D_SVT_SAMPLERCUBE,
	D3D10_SVT_PIXELSHADER = D3D_SVT_PIXELSHADER,
	D3D10_SVT_VERTEXSHADER = D3D_SVT_VERTEXSHADER,
	D3D10_SVT_PIXELFRAGMENT = D3D_SVT_PIXELFRAGMENT,
	D3D10_SVT_VERTEXFRAGMENT = D3D_SVT_VERTEXFRAGMENT,
	D3D10_SVT_UINT = D3D_SVT_UINT,
	D3D10_SVT_UINT8 = D3D_SVT_UINT8,
	D3D10_SVT_GEOMETRYSHADER = D3D_SVT_GEOMETRYSHADER,
	D3D10_SVT_RASTERIZER = D3D_SVT_RASTERIZER,
	D3D10_SVT_DEPTHSTENCIL = D3D_SVT_DEPTHSTENCIL,
	D3D10_SVT_BLEND = D3D_SVT_BLEND,
	D3D10_SVT_BUFFER = D3D_SVT_BUFFER,
	D3D10_SVT_CBUFFER = D3D_SVT_CBUFFER,
	D3D10_SVT_TBUFFER = D3D_SVT_TBUFFER,
	D3D10_SVT_TEXTURE1DARRAY = D3D_SVT_TEXTURE1DARRAY,
	D3D10_SVT_TEXTURE2DARRAY = D3D_SVT_TEXTURE2DARRAY,
	D3D10_SVT_RENDERTARGETVIEW = D3D_SVT_RENDERTARGETVIEW,
	D3D10_SVT_DEPTHSTENCILVIEW = D3D_SVT_DEPTHSTENCILVIEW,
	D3D10_SVT_TEXTURE2DMS = D3D_SVT_TEXTURE2DMS,
	D3D10_SVT_TEXTURE2DMSARRAY = D3D_SVT_TEXTURE2DMSARRAY,
	D3D10_SVT_TEXTURECUBEARRAY = D3D_SVT_TEXTURECUBEARRAY,
	D3D11_SVT_HULLSHADER = D3D_SVT_HULLSHADER,
	D3D11_SVT_DOMAINSHADER = D3D_SVT_DOMAINSHADER,
	D3D11_SVT_INTERFACE_POINTER = D3D_SVT_INTERFACE_POINTER,
	D3D11_SVT_COMPUTESHADER = D3D_SVT_COMPUTESHADER,
	D3D11_SVT_DOUBLE = D3D_SVT_DOUBLE,
	D3D11_SVT_RWTEXTURE1D = D3D_SVT_RWTEXTURE1D,
	D3D11_SVT_RWTEXTURE1DARRAY = D3D_SVT_RWTEXTURE1DARRAY,
	D3D11_SVT_RWTEXTURE2D = D3D_SVT_RWTEXTURE2D,
	D3D11_SVT_RWTEXTURE2DARRAY = D3D_SVT_RWTEXTURE2DARRAY,
	D3D11_SVT_RWTEXTURE3D = D3D_SVT_RWTEXTURE3D,
	D3D11_SVT_RWBUFFER = D3D_SVT_RWBUFFER,
	D3D11_SVT_BYTEADDRESS_BUFFER = D3D_SVT_BYTEADDRESS_BUFFER,
	D3D11_SVT_RWBYTEADDRESS_BUFFER = D3D_SVT_RWBYTEADDRESS_BUFFER,
	D3D11_SVT_STRUCTURED_BUFFER = D3D_SVT_STRUCTURED_BUFFER,
	D3D11_SVT_RWSTRUCTURED_BUFFER = D3D_SVT_RWSTRUCTURED_BUFFER,
	D3D11_SVT_APPEND_STRUCTURED_BUFFER = D3D_SVT_APPEND_STRUCTURED_BUFFER,
	D3D11_SVT_CONSUME_STRUCTURED_BUFFER = D3D_SVT_CONSUME_STRUCTURED_BUFFER,
	D3D_SVT_FORCE_DWORD = 0x7fffffff
};


enum class D3D_SHADER_INPUT_FLAGS
{
	D3D_SIF_USERPACKED = 0x1,
	D3D_SIF_COMPARISON_SAMPLER = 0x2,
	D3D_SIF_TEXTURE_COMPONENT_0 = 0x4,
	D3D_SIF_TEXTURE_COMPONENT_1 = 0x8,
	D3D_SIF_TEXTURE_COMPONENTS = 0xc,
	D3D_SIF_UNUSED = 0x10,
	D3D10_SIF_USERPACKED = D3D_SIF_USERPACKED,
	D3D10_SIF_COMPARISON_SAMPLER = D3D_SIF_COMPARISON_SAMPLER,
	D3D10_SIF_TEXTURE_COMPONENT_0 = D3D_SIF_TEXTURE_COMPONENT_0,
	D3D10_SIF_TEXTURE_COMPONENT_1 = D3D_SIF_TEXTURE_COMPONENT_1,
	D3D10_SIF_TEXTURE_COMPONENTS = D3D_SIF_TEXTURE_COMPONENTS,
	D3D_SIF_FORCE_DWORD = 0x7fffffff
};


enum class D3D_SHADER_INPUT_TYPE
{
	D3D_SIT_CBUFFER = 0,
	D3D_SIT_TBUFFER = (D3D_SIT_CBUFFER + 1),
	D3D_SIT_TEXTURE = (D3D_SIT_TBUFFER + 1),
	D3D_SIT_SAMPLER = (D3D_SIT_TEXTURE + 1),
	D3D_SIT_UAV_RWTYPED = (D3D_SIT_SAMPLER + 1),
	D3D_SIT_STRUCTURED = (D3D_SIT_UAV_RWTYPED + 1),
	D3D_SIT_UAV_RWSTRUCTURED = (D3D_SIT_STRUCTURED + 1),
	D3D_SIT_BYTEADDRESS = (D3D_SIT_UAV_RWSTRUCTURED + 1),
	D3D_SIT_UAV_RWBYTEADDRESS = (D3D_SIT_BYTEADDRESS + 1),
	D3D_SIT_UAV_APPEND_STRUCTURED = (D3D_SIT_UAV_RWBYTEADDRESS + 1),
	D3D_SIT_UAV_CONSUME_STRUCTURED = (D3D_SIT_UAV_APPEND_STRUCTURED + 1),
	D3D_SIT_UAV_RWSTRUCTURED_WITH_COUNTER = (D3D_SIT_UAV_CONSUME_STRUCTURED + 1),
	D3D10_SIT_CBUFFER = D3D_SIT_CBUFFER,
	D3D10_SIT_TBUFFER = D3D_SIT_TBUFFER,
	D3D10_SIT_TEXTURE = D3D_SIT_TEXTURE,
	D3D10_SIT_SAMPLER = D3D_SIT_SAMPLER,
	D3D11_SIT_UAV_RWTYPED = D3D_SIT_UAV_RWTYPED,
	D3D11_SIT_STRUCTURED = D3D_SIT_STRUCTURED,
	D3D11_SIT_UAV_RWSTRUCTURED = D3D_SIT_UAV_RWSTRUCTURED,
	D3D11_SIT_BYTEADDRESS = D3D_SIT_BYTEADDRESS,
	D3D11_SIT_UAV_RWBYTEADDRESS = D3D_SIT_UAV_RWBYTEADDRESS,
	D3D11_SIT_UAV_APPEND_STRUCTURED = D3D_SIT_UAV_APPEND_STRUCTURED,
	D3D11_SIT_UAV_CONSUME_STRUCTURED = D3D_SIT_UAV_CONSUME_STRUCTURED,
	D3D11_SIT_UAV_RWSTRUCTURED_WITH_COUNTER = D3D_SIT_UAV_RWSTRUCTURED_WITH_COUNTER
};


enum class D3D_SHADER_CBUFFER_FLAGS
{
	D3D_CBF_USERPACKED = 1,
	D3D10_CBF_USERPACKED = D3D_CBF_USERPACKED,
	D3D_CBF_FORCE_DWORD = 0x7fffffff
};


enum class D3D_CBUFFER_TYPE
{
	D3D_CT_CBUFFER = 0,
	D3D_CT_TBUFFER = (D3D_CT_CBUFFER + 1),
	D3D_CT_INTERFACE_POINTERS = (D3D_CT_TBUFFER + 1),
	D3D_CT_RESOURCE_BIND_INFO = (D3D_CT_INTERFACE_POINTERS + 1),
	D3D10_CT_CBUFFER = D3D_CT_CBUFFER,
	D3D10_CT_TBUFFER = D3D_CT_TBUFFER,
	D3D11_CT_CBUFFER = D3D_CT_CBUFFER,
	D3D11_CT_TBUFFER = D3D_CT_TBUFFER,
	D3D11_CT_INTERFACE_POINTERS = D3D_CT_INTERFACE_POINTERS,
	D3D11_CT_RESOURCE_BIND_INFO = D3D_CT_RESOURCE_BIND_INFO
};


enum class D3D_NAME
{
	D3D_NAME_UNDEFINED = 0,
	D3D_NAME_POSITION = 1,
	D3D_NAME_CLIP_DISTANCE = 2,
	D3D_NAME_CULL_DISTANCE = 3,
	D3D_NAME_RENDER_TARGET_ARRAY_INDEX = 4,
	D3D_NAME_VIEWPORT_ARRAY_INDEX = 5,
	D3D_NAME_VERTEX_ID = 6,
	D3D_NAME_PRIMITIVE_ID = 7,
	D3D_NAME_INSTANCE_ID = 8,
	D3D_NAME_IS_FRONT_FACE = 9,
	D3D_NAME_SAMPLE_INDEX = 10,
	D3D_NAME_FINAL_QUAD_EDGE_TESSFACTOR = 11,
	D3D_NAME_FINAL_QUAD_INSIDE_TESSFACTOR = 12,
	D3D_NAME_FINAL_TRI_EDGE_TESSFACTOR = 13,
	D3D_NAME_FINAL_TRI_INSIDE_TESSFACTOR = 14,
	D3D_NAME_FINAL_LINE_DETAIL_TESSFACTOR = 15,
	D3D_NAME_FINAL_LINE_DENSITY_TESSFACTOR = 16,
	D3D_NAME_BARYCENTRICS = 23,
	D3D_NAME_TARGET = 64,
	D3D_NAME_DEPTH = 65,
	D3D_NAME_COVERAGE = 66,
	D3D_NAME_DEPTH_GREATER_EQUAL = 67,
	D3D_NAME_DEPTH_LESS_EQUAL = 68,
	D3D_NAME_STENCIL_REF = 69,
	D3D_NAME_INNER_COVERAGE = 70,
	D3D10_NAME_UNDEFINED = D3D_NAME_UNDEFINED,
	D3D10_NAME_POSITION = D3D_NAME_POSITION,
	D3D10_NAME_CLIP_DISTANCE = D3D_NAME_CLIP_DISTANCE,
	D3D10_NAME_CULL_DISTANCE = D3D_NAME_CULL_DISTANCE,
	D3D10_NAME_RENDER_TARGET_ARRAY_INDEX = D3D_NAME_RENDER_TARGET_ARRAY_INDEX,
	D3D10_NAME_VIEWPORT_ARRAY_INDEX = D3D_NAME_VIEWPORT_ARRAY_INDEX,
	D3D10_NAME_VERTEX_ID = D3D_NAME_VERTEX_ID,
	D3D10_NAME_PRIMITIVE_ID = D3D_NAME_PRIMITIVE_ID,
	D3D10_NAME_INSTANCE_ID = D3D_NAME_INSTANCE_ID,
	D3D10_NAME_IS_FRONT_FACE = D3D_NAME_IS_FRONT_FACE,
	D3D10_NAME_SAMPLE_INDEX = D3D_NAME_SAMPLE_INDEX,
	D3D10_NAME_TARGET = D3D_NAME_TARGET,
	D3D10_NAME_DEPTH = D3D_NAME_DEPTH,
	D3D10_NAME_COVERAGE = D3D_NAME_COVERAGE,
	D3D11_NAME_FINAL_QUAD_EDGE_TESSFACTOR = D3D_NAME_FINAL_QUAD_EDGE_TESSFACTOR,
	D3D11_NAME_FINAL_QUAD_INSIDE_TESSFACTOR = D3D_NAME_FINAL_QUAD_INSIDE_TESSFACTOR,
	D3D11_NAME_FINAL_TRI_EDGE_TESSFACTOR = D3D_NAME_FINAL_TRI_EDGE_TESSFACTOR,
	D3D11_NAME_FINAL_TRI_INSIDE_TESSFACTOR = D3D_NAME_FINAL_TRI_INSIDE_TESSFACTOR,
	D3D11_NAME_FINAL_LINE_DETAIL_TESSFACTOR = D3D_NAME_FINAL_LINE_DETAIL_TESSFACTOR,
	D3D11_NAME_FINAL_LINE_DENSITY_TESSFACTOR = D3D_NAME_FINAL_LINE_DENSITY_TESSFACTOR,
	D3D11_NAME_DEPTH_GREATER_EQUAL = D3D_NAME_DEPTH_GREATER_EQUAL,
	D3D11_NAME_DEPTH_LESS_EQUAL = D3D_NAME_DEPTH_LESS_EQUAL,
	D3D11_NAME_STENCIL_REF = D3D_NAME_STENCIL_REF,
	D3D11_NAME_INNER_COVERAGE = D3D_NAME_INNER_COVERAGE,
	D3D12_NAME_BARYCENTRICS = D3D_NAME_BARYCENTRICS
};


enum class D3D_RESOURCE_RETURN_TYPE
{
	D3D_RETURN_TYPE_UNORM = 1,
	D3D_RETURN_TYPE_SNORM = 2,
	D3D_RETURN_TYPE_SINT = 3,
	D3D_RETURN_TYPE_UINT = 4,
	D3D_RETURN_TYPE_FLOAT = 5,
	D3D_RETURN_TYPE_MIXED = 6,
	D3D_RETURN_TYPE_DOUBLE = 7,
	D3D_RETURN_TYPE_CONTINUED = 8,
	D3D10_RETURN_TYPE_UNORM = D3D_RETURN_TYPE_UNORM,
	D3D10_RETURN_TYPE_SNORM = D3D_RETURN_TYPE_SNORM,
	D3D10_RETURN_TYPE_SINT = D3D_RETURN_TYPE_SINT,
	D3D10_RETURN_TYPE_UINT = D3D_RETURN_TYPE_UINT,
	D3D10_RETURN_TYPE_FLOAT = D3D_RETURN_TYPE_FLOAT,
	D3D10_RETURN_TYPE_MIXED = D3D_RETURN_TYPE_MIXED,
	D3D11_RETURN_TYPE_UNORM = D3D_RETURN_TYPE_UNORM,
	D3D11_RETURN_TYPE_SNORM = D3D_RETURN_TYPE_SNORM,
	D3D11_RETURN_TYPE_SINT = D3D_RETURN_TYPE_SINT,
	D3D11_RETURN_TYPE_UINT = D3D_RETURN_TYPE_UINT,
	D3D11_RETURN_TYPE_FLOAT = D3D_RETURN_TYPE_FLOAT,
	D3D11_RETURN_TYPE_MIXED = D3D_RETURN_TYPE_MIXED,
	D3D11_RETURN_TYPE_DOUBLE = D3D_RETURN_TYPE_DOUBLE,
	D3D11_RETURN_TYPE_CONTINUED = D3D_RETURN_TYPE_CONTINUED
};


enum class D3D_REGISTER_COMPONENT_TYPE
{
	D3D_REGISTER_COMPONENT_UNKNOWN = 0,
	D3D_REGISTER_COMPONENT_UINT32 = 1,
	D3D_REGISTER_COMPONENT_SINT32 = 2,
	D3D_REGISTER_COMPONENT_FLOAT32 = 3,
	D3D10_REGISTER_COMPONENT_UNKNOWN = D3D_REGISTER_COMPONENT_UNKNOWN,
	D3D10_REGISTER_COMPONENT_UINT32 = D3D_REGISTER_COMPONENT_UINT32,
	D3D10_REGISTER_COMPONENT_SINT32 = D3D_REGISTER_COMPONENT_SINT32,
	D3D10_REGISTER_COMPONENT_FLOAT32 = D3D_REGISTER_COMPONENT_FLOAT32
};


enum class D3D_TESSELLATOR_DOMAIN
{
	D3D_TESSELLATOR_DOMAIN_UNDEFINED = 0,
	D3D_TESSELLATOR_DOMAIN_ISOLINE = 1,
	D3D_TESSELLATOR_DOMAIN_TRI = 2,
	D3D_TESSELLATOR_DOMAIN_QUAD = 3,
	D3D11_TESSELLATOR_DOMAIN_UNDEFINED = D3D_TESSELLATOR_DOMAIN_UNDEFINED,
	D3D11_TESSELLATOR_DOMAIN_ISOLINE = D3D_TESSELLATOR_DOMAIN_ISOLINE,
	D3D11_TESSELLATOR_DOMAIN_TRI = D3D_TESSELLATOR_DOMAIN_TRI,
	D3D11_TESSELLATOR_DOMAIN_QUAD = D3D_TESSELLATOR_DOMAIN_QUAD
};


enum class D3D_TESSELLATOR_PARTITIONING
{
	D3D_TESSELLATOR_PARTITIONING_UNDEFINED = 0,
	D3D_TESSELLATOR_PARTITIONING_INTEGER = 1,
	D3D_TESSELLATOR_PARTITIONING_POW2 = 2,
	D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD = 3,
	D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN = 4,
	D3D11_TESSELLATOR_PARTITIONING_UNDEFINED = D3D_TESSELLATOR_PARTITIONING_UNDEFINED,
	D3D11_TESSELLATOR_PARTITIONING_INTEGER = D3D_TESSELLATOR_PARTITIONING_INTEGER,
	D3D11_TESSELLATOR_PARTITIONING_POW2 = D3D_TESSELLATOR_PARTITIONING_POW2,
	D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD = D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD,
	D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN = D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN
};


enum class D3D_TESSELLATOR_OUTPUT_PRIMITIVE
{
	D3D_TESSELLATOR_OUTPUT_UNDEFINED = 0,
	D3D_TESSELLATOR_OUTPUT_POINT = 1,
	D3D_TESSELLATOR_OUTPUT_LINE = 2,
	D3D_TESSELLATOR_OUTPUT_TRIANGLE_CW = 3,
	D3D_TESSELLATOR_OUTPUT_TRIANGLE_CCW = 4,
	D3D11_TESSELLATOR_OUTPUT_UNDEFINED = D3D_TESSELLATOR_OUTPUT_UNDEFINED,
	D3D11_TESSELLATOR_OUTPUT_POINT = D3D_TESSELLATOR_OUTPUT_POINT,
	D3D11_TESSELLATOR_OUTPUT_LINE = D3D_TESSELLATOR_OUTPUT_LINE,
	D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CW = D3D_TESSELLATOR_OUTPUT_TRIANGLE_CW,
	D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CCW = D3D_TESSELLATOR_OUTPUT_TRIANGLE_CCW
};


enum class D3D_MIN_PRECISION
{
	D3D_MIN_PRECISION_DEFAULT = 0,
	D3D_MIN_PRECISION_FLOAT_16 = 1,
	D3D_MIN_PRECISION_FLOAT_2_8 = 2,
	D3D_MIN_PRECISION_RESERVED = 3,
	D3D_MIN_PRECISION_SINT_16 = 4,
	D3D_MIN_PRECISION_UINT_16 = 5,
	D3D_MIN_PRECISION_ANY_16 = 0xf0,
	D3D_MIN_PRECISION_ANY_10 = 0xf1
};


enum class D3D_INTERPOLATION_MODE
{
	D3D_INTERPOLATION_UNDEFINED = 0,
	D3D_INTERPOLATION_CONSTANT = 1,
	D3D_INTERPOLATION_LINEAR = 2,
	D3D_INTERPOLATION_LINEAR_CENTROID = 3,
	D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE = 4,
	D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE_CENTROID = 5,
	D3D_INTERPOLATION_LINEAR_SAMPLE = 6,
	D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE_SAMPLE = 7
};


enum class D3D_PARAMETER_FLAGS
{
	D3D_PF_NONE = 0,
	D3D_PF_IN = 0x1,
	D3D_PF_OUT = 0x2,
	D3D_PF_FORCE_DWORD = 0x7fffffff
};

constexpr uint32_t DXGI_CPU_ACCESS_NONE = 0;
constexpr uint32_t DXGI_CPU_ACCESS_DYNAMIC = 1;
constexpr uint32_t DXGI_CPU_ACCESS_READ_WRITE = 2;
constexpr uint32_t DXGI_CPU_ACCESS_SCRATCH = 3;
constexpr uint32_t DXGI_CPU_ACCESS_FIELD = 15;

enum class DXGI_USAGE
{
	DXGI_USAGE_SHADER_INPUT = 0x00000010UL,
	DXGI_USAGE_RENDER_TARGET_OUTPUT = 0x00000020UL,
	DXGI_USAGE_BACK_BUFFER = 0x00000040UL,
	DXGI_USAGE_SHARED = 0x00000080UL,
	DXGI_USAGE_READ_ONLY = 0x00000100UL,
	DXGI_USAGE_DISCARD_ON_PRESENT = 0x00000200UL,
	DXGI_USAGE_UNORDERED_ACCESS = 0x00000400UL,
};
REGIST_ENUM_FLAG(DXGI_USAGE);

struct DXGI_RATIONAL
{
	uint32_t Numerator;
	uint32_t Denominator;
};

struct DXGI_RGB
{
	float Red;
	float Green;
	float Blue;
};

struct D3DCOLORVALUE {
	float r;
	float g;
	float b;
	float a;
};

using DXGI_RGBA = D3DCOLORVALUE;

struct DXGI_GAMMA_CONTROL
{
	DXGI_RGB Scale;
	DXGI_RGB Offset;
	DXGI_RGB GammaCurve[1025];
};

struct DXGI_GAMMA_CONTROL_CAPABILITIES
{
	uint32_t ScaleAndOffsetSupported;
	float MaxConvertedValue;
	float MinConvertedValue;
	uint32_t NumGammaControlPoints;
	float ControlPointPositions[1025];
};

enum class DXGI_MODE_SCANLINE_ORDER
{
	DXGI_MODE_SCANLINE_ORDER_UNSPECIFIED = 0,
	DXGI_MODE_SCANLINE_ORDER_PROGRESSIVE = 1,
	DXGI_MODE_SCANLINE_ORDER_UPPER_FIELD_FIRST = 2,
	DXGI_MODE_SCANLINE_ORDER_LOWER_FIELD_FIRST = 3
};

enum class DXGI_MODE_SCALING
{
	DXGI_MODE_SCALING_UNSPECIFIED = 0,
	DXGI_MODE_SCALING_CENTERED = 1,
	DXGI_MODE_SCALING_STRETCHED = 2
};

enum class DXGI_MODE_ROTATION
{
	DXGI_MODE_ROTATION_UNSPECIFIED = 0,
	DXGI_MODE_ROTATION_IDENTITY = 1,
	DXGI_MODE_ROTATION_ROTATE90 = 2,
	DXGI_MODE_ROTATION_ROTATE180 = 3,
	DXGI_MODE_ROTATION_ROTATE270 = 4
};

struct DXGI_MODE_DESC
{
	uint32_t Width;
	uint32_t Height;
	DXGI_RATIONAL RefreshRate;
	DXGI_FORMAT Format;
	DXGI_MODE_SCANLINE_ORDER ScanlineOrdering;
	DXGI_MODE_SCALING Scaling;
};

struct DXGI_JPEG_DC_HUFFMAN_TABLE
{
	uint8_t CodeCounts[12];
	uint8_t CodeValues[12];
};

struct DXGI_JPEG_AC_HUFFMAN_TABLE
{
	uint8_t CodeCounts[16];
	uint8_t CodeValues[162];
};

struct DXGI_JPEG_QUANTIZATION_TABLE
{
	uint8_t Elements[64];
};

struct DXGI_FRAME_STATISTICS
{
	uint32_t PresentCount;
	uint32_t PresentRefreshCount;
	uint32_t SyncRefreshCount;
	int64_t SyncQPCTime;
	int64_t SyncGPUTime;
};

struct DXGI_MAPPED_RECT
{
	int32_t Pitch;
	uint8_t* pBits;
};

struct DXGI_ADAPTER_DESC
{
	wchar_t Description[128];
	uint32_t VendorId;
	uint32_t DeviceId;
	uint32_t SubSysId;
	uint32_t Revision;
	size_t DedicatedVideoMemory;
	size_t DedicatedSystemMemory;
	size_t SharedSystemMemory;
	int64_t AdapterLuid;
};


struct DXGI_OUTPUT_DESC
{
	wchar_t DeviceName[32];
	RECT DesktopCoordinates;
	uint32_t AttachedToDesktop;
	DXGI_MODE_ROTATION Rotation;
	HMONITOR Monitor;
};

struct DXGI_SHARED_RESOURCE
{
	HANDLE Handle;
};

constexpr uint32_t	DXGI_RESOURCE_PRIORITY_MINIMUM = 0x28000000;
constexpr uint32_t	DXGI_RESOURCE_PRIORITY_LOW = 0x50000000;
constexpr uint32_t	DXGI_RESOURCE_PRIORITY_NORMAL = 0x78000000;
constexpr uint32_t	DXGI_RESOURCE_PRIORITY_HIGH = 0xa0000000;
constexpr uint32_t	DXGI_RESOURCE_PRIORITY_MAXIMUM = 0xc8000000;


enum class DXGI_RESIDENCY
{
	DXGI_RESIDENCY_FULLY_RESIDENT = 1,
	DXGI_RESIDENCY_RESIDENT_IN_SHARED_MEMORY = 2,
	DXGI_RESIDENCY_EVICTED_TO_DISK = 3
};

struct DXGI_SURFACE_DESC
{
	uint32_t Width;
	uint32_t Height;
	DXGI_FORMAT Format;
	DXGI_SAMPLE_DESC SampleDesc;
};


enum class DXGI_SWAP_EFFECT
{
	DXGI_SWAP_EFFECT_DISCARD = 0,
	DXGI_SWAP_EFFECT_SEQUENTIAL = 1,
	DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL = 3,
	DXGI_SWAP_EFFECT_FLIP_DISCARD = 4
};


enum class DXGI_SWAP_CHAIN_FLAG : uint32_t
{
	DXGI_SWAP_CHAIN_FLAG_NONE = 0,
	DXGI_SWAP_CHAIN_FLAG_NONPREROTATED = 1,
	DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH = 2,
	DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE = 4,
	DXGI_SWAP_CHAIN_FLAG_RESTRICTED_CONTENT = 8,
	DXGI_SWAP_CHAIN_FLAG_RESTRICT_SHARED_RESOURCE_DRIVER = 16,
	DXGI_SWAP_CHAIN_FLAG_DISPLAY_ONLY = 32,
	DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT = 64,
	DXGI_SWAP_CHAIN_FLAG_FOREGROUND_LAYER = 128,
	DXGI_SWAP_CHAIN_FLAG_FULLSCREEN_VIDEO = 256,
	DXGI_SWAP_CHAIN_FLAG_YUV_VIDEO = 512,
	DXGI_SWAP_CHAIN_FLAG_HW_PROTECTED = 1024,
	DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING = 2048,
	DXGI_SWAP_CHAIN_FLAG_RESTRICTED_TO_ALL_HOLOGRAPHIC_DISPLAYS = 4096
};

REGIST_ENUM_FLAG(DXGI_SWAP_CHAIN_FLAG)

struct DXGI_SWAP_CHAIN_DESC
{
	DXGI_MODE_DESC BufferDesc;
	DXGI_SAMPLE_DESC SampleDesc;
	DXGI_USAGE BufferUsage;
	uint32_t BufferCount;
	HWND OutputWindow;
	uint32_t Windowed;
	DXGI_SWAP_EFFECT SwapEffect;
	DXGI_SWAP_CHAIN_FLAG Flags;
};


constexpr uint32_t	DXGI_MAP_READ = 1UL;

constexpr uint32_t	DXGI_MAP_WRITE = 2UL;

constexpr uint32_t	DXGI_MAP_DISCARD = 4UL;

constexpr uint32_t DXGI_MAX_SWAP_CHAIN_BUFFERS = 16;
constexpr uint32_t DXGI_PRESENT_TEST = 0x00000001UL;
constexpr uint32_t DXGI_PRESENT_DO_NOT_SEQUENCE = 0x00000002UL;
constexpr uint32_t DXGI_PRESENT_RESTART = 0x00000004UL;
constexpr uint32_t DXGI_PRESENT_DO_NOT_WAIT = 0x00000008UL;
constexpr uint32_t DXGI_PRESENT_STEREO_PREFER_RIGHT = 0x00000010UL;
constexpr uint32_t DXGI_PRESENT_STEREO_TEMPORARY_MONO = 0x00000020UL;
constexpr uint32_t DXGI_PRESENT_RESTRICT_TO_OUTPUT = 0x00000040UL;
constexpr uint32_t DXGI_PRESENT_USE_DURATION = 0x00000100UL;
constexpr uint32_t DXGI_PRESENT_ALLOW_TEARING = 0x00000200UL;

constexpr uint32_t DXGI_MWA_NO_WINDOW_CHANGES = 1 << 0;
constexpr uint32_t DXGI_MWA_NO_ALT_ENTER = 1 << 1;
constexpr uint32_t DXGI_MWA_NO_PRint32_t_SCREEN = 1 << 2;
constexpr uint32_t DXGI_MWA_VALID = 0x7;

enum class DXGI_ADAPTER_FLAG : uint32_t
{
	DXGI_ADAPTER_FLAG_NONE = 0,
	DXGI_ADAPTER_FLAG_REMOTE = 1,
	DXGI_ADAPTER_FLAG_SOFTWARE = 2,
	DXGI_ADAPTER_FLAG_FORCE_DWORD = 0xffffffff
};

struct DXGI_ADAPTER_DESC1
{
	wchar_t Description[128];
	uint32_t VendorId;
	uint32_t DeviceId;
	uint32_t SubSysId;
	uint32_t Revision;
	size_t DedicatedVideoMemory;
	size_t DedicatedSystemMemory;
	size_t SharedSystemMemory;
	int64_t AdapterLuid;
	uint32_t Flags;
};

struct DXGI_DISPLAY_COLOR_SPACE
{
	float PrimaryCoordinates[8][2];
	float WhitePoints[16][2];
};

